Counter=10

[Command_2]
Command=seek -5
Order=0
OsdMessage=
Type=shortcut

[Command_3]
Command=seek 5
Order=1
OsdMessage=
Type=shortcut

[Command_4]
Command=seek -30
Order=2
OsdMessage=
Type=shortcut

[Command_5]
Command=seek 30
Order=3
OsdMessage=
Type=shortcut
