[Audio]
Volume=100

[General]
ColorScheme=Breeze Dark
FooterStyle=floating
GuiStyle=Breeze
MaxRecentFiles=0
OsdFontSize=16
ShowHeader=false
ShowMenuBar=false

[Mouse]
Back=playPreviousAction
Forward=playNextAction
Left=
Middle=quitApplicationAction
Right=playPauseAction
ScrollDown=seekBackwardSmallAction
ScrollUp=seekForwardSmallAction

[Playback]
YtdlFormat=bestvideo[height<=1080]+bestaudio/best

[Playlist]
BigFontFullscreen=false
CanToggleWithMouse=false
LoadSiblings=false
PlaylistWidth=364

[Subtitles]
FontFamily=Noto Sans
FontSize=32
PreferredLanguage=eng
