[Shortcuts]
Command_2=A
Command_3=D
Command_4=S
Command_5=W
openActionsDialogAction=Ctrl+Shift+P
playNextAction=Ctrl+Tab
playPreviousAction=Ctrl+Shift+Tab
quitApplicationAction=Q
screenshotAction=
seekToWatchLaterPositionAction=
subtitleToggleAction=V
toggleDeinterlacingAction=
volumeDownAction=9
volumeUpAction=0
