#! /usr/bin/env bash

rm -r $HOME/.cache/thumbnails/*
rm -r $HOME/.cache/ueberzugpp/*
rm -r $HOME/.var/app/org.kde.dolphin/cache/thumbnails/*
rm -r /tmp/yazi*

rm $HOME/.local/share/recently-used.xbel
rm $HOME/.local/share/qBittorrent/logs/qbittorrent.log
rm $HOME/.local/share/ark/ark_recentfiles

pkill copyq
copyq &
