#! /usr/bin/env bash

selected=$(
    {
        printf "Laptop Display\nSecond Display\nDuplicate\n"
        printf "Dual Display (Right) (primary: HDMI)\n"
        printf "Dual Display (Left) (primary: HDMI)\n"
    } | dmenu -c -i -z 500 -l 8 -p "display:"
)

case "$selected" in
    "Laptop Display") laptop_display ;;
    "Second Display") second_display ;;
    "Duplicate")      duplicate_display ;;
    "Dual Display (Right) (primary: HDMI)") dual_right_display;;
    "Dual Display (Left) (primary: HDMI)")  dual_left_display;;
esac
