#!/usr/bin/env bash

all_apps=$(dmenu_path)
flatpak_apps=$(flatpak list --app --columns=application)

selected=$(
    {
        printf "Spotify\nPrivate\n"
        flatpak list --app --columns=application
        dmenu_path
    } | dmenu -i -c -z 800 -l 8 -p "run:"
)

if [[ -n "$selected" ]]; then
    if flatpak info "$selected" &>/dev/null; then
        flatpak run "$selected" &
    else
        case "$selected" in
            Spotify)    firefox --new-window open.spotify.com ;;
            Private)    firefox --private-window ;;
            *)          $selected &>/dev/null & ;;
        esac
    fi
fi
