#!/bin/sh
xrandr --output eDP1 --auto --left-of HDMI-1-0 --rotate normal --output VIRTUAL1 --off --output HDMI-1-0 --primary --auto --rotate normal
~/dotfiles/.local/scripts/change_wallpaper.sh # refresh the wallpaper
