#!/bin/sh
xrandr --output eDP-1 --auto --right-of HDMI-1-0 --rotate normal --output HDMI-1-0 --primary --auto --pos 0x0 --rotate normal
~/dotfiles/.local/scripts/change_wallpaper.sh # refresh the wallpaper
