#!/usr/bin/env bash

find . -name '*.vtt' -print0 |
while IFS= read -r -d '' file; do
    sed -i \
        -e 's/？/?/g' \
        -e 's/！/!/g' \
        -e 's/，/,/g' \
        -e 's/。/./g' \
        -e 's/：/:/g' \
        -e 's/；/;/g' \
        -e 's/（/(/g' \
        -e 's/）/)/g' \
        "$file"
done
