#!/usr/bin/env bash

i3lock \
    --image="$HOME/pictures/wallpapers/stellar-blade-blood-rain-evie-0-blur.jpg" \
    --fill \
    --radius=200 \
    --clock \
    --time-str="%H:%M" \
    --date-str="%a • %b %d, %Y" \
    --time-color="#ffffff" \
    --date-color="#e0e0e0" \
    --timeoutline-color="#282828aa" \
    --dateoutline-color="#282828aa" \
    --dateoutline-width=1\
    --timeoutline-width=1\
    --time-size=80 \
    --date-size=40 \
    --date-pos="tx:ty+44" \
    --insidever-color="#458588bf" \
    --ringver-color="#458588ff" \
    --insidewrong-color="#CC241Dbf" \
    --ringwrong-color="#CC241Dff" \
    --verif-color="#ffffff" \
    --verifoutline-color="#282828" \
    --wrong-color="#ffffff" \
    --wrongoutline-color="#282828" \
    --verif-size=40\
    --wrong-size=40\
    --pass-media \
    --pass-volume
