#!/usr/bin/env bash

#---- Usage -----
# tmuxinit session_name
# OR, if no arg is provided, the directory name will be used as the session name
# tmuxinit

# Use argument if provided, otherwise use current directory name
if [ -n "$1" ]; then
    SESSION_NAME="$1"
else
    DIR_NAME="$(basename "$PWD")"
    SESSION_NAME="${DIR_NAME:0:5}"
fi

# Check if Python venv exists
IS_PYTHON_ENV=$([ -d .env ] && echo true || echo false)

# Check if nvim session file exists
IS_NVIM_SESSION=$([ -e session.vim ] && echo true || echo false)

# Check if session already exists
tmux has-session -t "$SESSION_NAME" 2>/dev/null

if [ $? != 0 ]; then
    # Window 0: nvim
    tmux new-session -d -s "$SESSION_NAME" -n nvim
    if [ "$IS_PYTHON_ENV" = true ]; then
        tmux send-keys -t "$SESSION_NAME:0" "source .env/bin/activate" C-m
    fi

    if [ "$IS_NVIM_SESSION" = true ]; then
        tmux send-keys -t "$SESSION_NAME:0" "nvim -S session.vim" C-m
    else
        tmux send-keys -t "$SESSION_NAME:0" "nvim ." C-m
    fi

    # Window 1: term
    tmux new-window -t "$SESSION_NAME:1" -n term
    if [ "$IS_PYTHON_ENV" = true ]; then
        tmux send-keys -t "$SESSION_NAME:1" "source .env/bin/activate" C-m
    fi

    # Window 2: git
    tmux new-window -t "$SESSION_NAME:2" -n git
    if [ "$IS_PYTHON_ENV" = true ]; then
        tmux send-keys -t "$SESSION_NAME:2" "source .env/bin/activate" C-m
    fi
    tmux send-keys -t "$SESSION_NAME:2" "lazygit" C-m

    # Window 3: file manager
    tmux new-window -t "$SESSION_NAME:3" -n files
    if [ "$IS_PYTHON_ENV" = true ]; then
        tmux send-keys -t "$SESSION_NAME:3" "source .env/bin/activate" C-m
    fi
    tmux send-keys -t "$SESSION_NAME:3" "y" C-m  # open yazi
fi

# Always start in first window
tmux select-window -t "$SESSION_NAME:0"
# Attach to session
tmux attach -t "$SESSION_NAME"
