return {
  --   "nvim-tree/nvim-tree.lua",
  --   lazy = false,
  --   dependencies = {
  --     "nvim-tree/nvim-web-devicons",
  --   },
  --   config = function()
  --     require("nvim-tree").setup({
  --       git = {
  --         ignore = false,
  --       },
  --       actions = {
  --         open_file = {
  --           quit_on_open = true,
  --         },
  --       },
  --       renderer = {
  --         icons = {
  --           show = {
  --             file = true,
  --             folder = true,
  --             folder_arrow = true,
  --             git = false,
  --             modified = false,
  --           },
  --         }
  --       },
  --       view = {
  --         number = true,
  --         relativenumber = true,
  --         width = 42,
  --       },
  --       on_attach = function(bufnr)
  --         local api = require("nvim-tree.api")
  --         local opts = { buffer = bufnr }
  --         api.config.mappings.default_on_attach(bufnr)
  --         -- function for left to assign to keybindings
  --         local lefty = function()
  --           local node_at_cursor = api.tree.get_node_under_cursor()
  --           -- if it's a node and it's open, close
  --           if node_at_cursor.nodes and node_at_cursor.open then
  --             api.node.open.edit()
  --             -- else left jumps up to parent
  --           else
  --             api.node.navigate.parent()
  --           end
  --         end
  --         -- function for right to assign to keybindings
  --         local righty = function()
  --           local node_at_cursor = api.tree.get_node_under_cursor()
  --           -- if it's a closed node, open it
  --           if node_at_cursor.nodes and not node_at_cursor.open then
  --             api.node.open.edit()
  --           end
  --         end
  --         vim.keymap.set("n", "h", lefty, opts)
  --         vim.keymap.set("n", "<Left>", lefty, opts)
  --         vim.keymap.set("n", "<Right>", righty, opts)
  --         vim.keymap.set("n", "l", righty, opts)
  --         vim.keymap.del("n", "<C-e>", opts)
  --       end,
  --     })
  --   end,
}
