-- require('telescope').setup({
--   defaults = {
--     mappings = {
--       i = {
--         ["<esc>"] = require('telescope.actions').close,         -- Esc to close telescope in insert mode
--         ["<C-h>"] = function() vim.api.nvim_input("<C-w>") end, -- Ctrl + Backspace
--       },
--     }
--   }
-- })
-- vim.keymap.set('n', '<leader>ff', function()
--   require('telescope.builtin').find_files({ hidden = true, no_ignore = false })
-- end, { desc = "Find files" })
-- vim.keymap.set('n', '<leader>fg', require('telescope.builtin').live_grep, { desc = "Live grep" })
-- vim.keymap.set('n', '<leader>fs', require('telescope.builtin').grep_string,
--   { desc = "Grep string under the cursor or selection" })
-- vim.keymap.set('n', '<leader>fc', require('telescope.builtin').current_buffer_fuzzy_find,
--   { desc = "Fuzzy find in current buffer" })
-- vim.keymap.set('n', '<leader>fG', require('telescope.builtin').git_files, { desc = "Git files" })
-- vim.keymap.set('n', '<leader>fb', require('telescope.builtin').buffers, { desc = "Buffers" })
-- vim.keymap.set('n', '<leader>fh', require('telescope.builtin').help_tags, { desc = "Help tags" })
